version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4900:4900"  # Port to access the Go API
    volumes:
      - ./api:/app
      - /app/go_modules  # Use a separate volume to store Go modules (optional)
    environment:
      - GO_ENV=development
    command: bash -c "go run /app/api/main.go"
